export const LOGIN_LOADING = "LOGIN_LOADING";
export const LOGIN_ERROR = "LOGIN_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_ADD = "LOGIN_ADD";

export const REGISTER_LOADING = "REGISTER_LOADING";
export const REGISTER_ERROR = "REGISTER_ERROR";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";

export const HISTORY_LOADING = "HISTORY_LOADING";
export const HISTORY_ERROR = "HISTORY_ERROR";
export const HISTORY_SUCCESS = "HISTORY_SUCCESS";

export const MESSAGE_LOADING = "HISTORY_LOADING";
export const MESSAGE_ERROR = "MESSAGE_ERROR";
export const MESSAGE_SUCCESS = "MESSAGE_SUCCESS";
